export const ProductStores=[
    {
        "id":1,
        "title":"Cashew Nut",
         "price":1000,
        "Image":"/images/cashew.jfif",
         "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
         "Incart":false,
          "count":0,
          "total":0,
          "category":"Export",
          "company":"HollywayGlobal",
           label:1,
     },{
        "id":2,
        "title":"Cassava",
         "price":500,
        "Image":"/images/cassava.jpg",
         "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
         "Incart":false,
          "count":0,
          "total":0,
          "category":"Local",
          "company":"HollywayGlobal",
           label:1
     },{
        "id":3,
        "title":"CocoaSeed",
         "price":2000,
        "Image":"/images/cocoaSeed.jpg",
         "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
         "Incart":false,
          "count":0,
          "total":0,
          "category":"Local",
          "company":"HollywayGlobal",
           label:1
     },{
        "id":4,
        "title":"CocoaYam",
         "price":200,
        "Image":"/images/cocoayam.jpg",
         "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
         "Incart":false,
          "count":0,
          "total":0,
          "category":"Local",
          "company":"HollywayGlobal",
           label:1
    
     },{
         "id":5,
        "title":"Cow",
         "price":2500,
        "Image":"/images/cow.jpg",
         "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
         "Incart":false,
          "count":0,
          "total":0,
          "category":"local",
          "company":"HollywayGlobal",
           label:1
         },{
         "id":6,
        "title":"Corn",
         "price":200,
        "Image":"/images/corn.jpg",
         "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
         "Incart":false,
          "count":0,
          "total":0,
          "category":"Export",
          "company":"HollywayGlobal",
           label:1
    
     },{
         "id":7,
         "title":"Bitter Leaf",
          "price":100,
          "Image":"/images/bitter leaf.jfif",
          "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
          "Incart":false,
          "count":0,
          "total":0,
          "category":"Export",
          "company":"HollywayGlobal",
           label:1          
         },{
         "id":8,
         "title":"Pepper",
          "price":7000,
         "Image":"/images/pepper.jpg",
          "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
          "Incart":false,
          "count":0,
          "total":0,
          "category":"Export",
          "company":"HollywayGlobal",
           label:1
         },{
         "id":9,
        "title":"Beans",
         "price":600,
        "Image":"/images/beans.jpg",
         "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
         "Incart":false,
          "count":0,
          "total":0,
          "category":"Local",
          "company":"HollywayGlobal",
           label:1
         },{
         "id":10,
         "title":"Banana",
          "price":3070,
         "Image":"/images/banana.jpg",
          "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
          "Incart":false,
          "count":0,
          "total":0,
          "category":"Local",
          "company":"HollywayGlobal",
           label:1
         },{
         "id":11,
         "title":"Carrot",
          "price":770,
         "Image":"/images/carrot.jpg",
          "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
          "Incart":false,
          "count":0,
          "total":0,
          "category":"Local",
          "company":"HollywayGlobal",
           label:1
         },{
         "id":12,
         "title":"CatFish",
          "price":7800,
         "Image":"/images/catsfish.jpg",
          "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
          "Incart":false,
          "count":0,
          "total":0,
          "category":"Export",
          "company":"HollywayGlobal",
           label:1     
         },{
         "id":14,
         "title":"Drip",
          "price":9000,
         "Image":"/images/drip.jfif",
          "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
          "Incart":false,
          "count":0,
          "total":0,
          "category":"Export",
          "company":"HollywayGlobal",
           label:1
     },{
         "id":15,
         "title":"Eggs Tray",
          "price":780,
         "Image":"/images/createEgg.jpg",
          "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
          "Incart":false,
          "count":0,
          "total":0,
          "category":"Local",
          "company":"HollywayGlobal",
           label:1
     },{
          "id":16,
          "title":"Drum",
           "price":10890,
          "Image":"/images/drum.jfif",
           "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
           "Incart":false,
           "count":0,
           "total":0,
           "category":"Local",
          "company":"HollywayGlobal",
           label:1
      },{
          "id":17,
          "title":"Force Up",
           "price":1090,
          "Image":"/images/forceup.jpg",
           "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
           "Incart":false,
           "count":0,
           "total":0,
           "category":"Export",
          "company":"HollywayGlobal",
           label:1  
      },{
          "id":18,
          "title":"Cucumber",
           "price":1790,
          "Image":"/images/cucumber.jpg",
           "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
           "Incart":false,
           "count":0,
           "total":0,
           "category":"Export",
          "company":"HollywayGlobal",
           label:1 
      },{
        "id":19,
        "title":"Okro",
         "price":1490,
        "Image":"/images/okro.jfif",
         "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
         "Incart":false,
         "count":0,
         "total":0,
         "category":"HotDeals",
         "company":"HollywayGlobal",
          label:1 
      },{
        "id":20,
        "title":"Rice Paddy",
         "price":121,
        "Image":"/images/ricePaddy2.jpg",
         "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
         "Incart":false,
         "count":0,
         "total":0,
         "category":"HotDeals",
         "company":"HollywayGlobal",
         label:1
      },{
        "id":21,
        "title":"Fresh Pepper",
         "price":190,
        "Image":"/images/rodo.jfif",
         "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
         "Incart":false,
         "count":0,
         "total":0,
         "category":"HotDeals",
         "company":"HollywayGlobal",
         label:1
      },{
        "id":22,
        "title":"Seeder",
         "price":140,
        "Image":"/images/seeder.jfif",
         "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
         "Incart":false,
         "count":0,
         "total":0,
         "category":"HotDeals",
         "company":"HollywayGlobal",
         label:1
      }
]
export const DetailProduct={
        "id":1,
        "title":"Cashew Nut",
        "price":1000,
        "Image":"/images/cashew.jfif",
        "info":"Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque vero doloremque quia dignissimos consequuntur porro aspernatur eum optio laboriosam consequatur! Consequatur quibusdam adipisci quaerat ullam dicta rem illo tempora ea sunt doloremque nostrum dolor dolorum quo, sequi eveniet voluptatem laboriosam possimus. Maxime minus, dicta necessitatibus eos voluptatum laborum dolorem recusandae",
        "Incart":false,
        "count":0,
        "total":0,
        "company":"HollywayGlobal",
        label:1
}


